### Register as ADMIN (success)

@admin_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkNmU5MmQyYS1lOGJhLTQ5NjctODFiZS0zNmZjODFmNDAwZjAiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzUxNTc0ODAzfQ.5MZQ2A-OLsP3AE7C4Ai_TmoqfjXLALOln0H12rnwSvE
@encadrant_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwZjI3MDlmMy02MjI0LTRlMWQtYWIwZS05NTgwNWJjZTk4NDQiLCJlbWFpbCI6ImVuY2FkcmFudEBleGFtcGxlLmNvbSIsInJvbGUiOiJlbmNhZHJhbnQiLCJleHAiOjE3NTE1NzQ4MzZ9.0EFut7hMZrmlZUG-HtXZ_6TQGROGF6KWQC6Nxg_BDkQ
@etudiant_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3YTM3MTk1Ny1hZWE3LTRlMTQtOTllOS1hNzIyMTBmMWNhNGYiLCJlbWFpbCI6ImV0dWRpYW50MUBleGFtcGxlLmNvbSIsInJvbGUiOiJldHVkaWFudCIsImV4cCI6MTc1MTU3NDg4Mn0.OMtl5Re05wVRvjm9HbJqA3HIqs_0a--2lUUanpHkVqw

@incube_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3ZmEwOGY5MC0xZWJkLTRlNmItODdlMS0zNzg4YzkzNDkzMTciLCJlbWFpbCI6ImZyaWhhb3VpbW9oYW1lZEBnbWFpbC5jb20iLCJyb2xlIjoiaW5jdWJlIiwiZXhwIjoxNzUxNTc1ODU5fQ.s-75hoS8PfM-cHrJQAe_1MedDFy_3aWkm9IZOFP1iUc

POST http://localhost:4000/auth/register
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "email": "encadrant@example.com",
  "nom": "Mentor",
  "prenom": "Encadrant",
  "password": "password123",
  "role": "Encadrant"
}

### Register as ENCADRANT (success)
POST http://localhost:4000/auth/register
Authorization: Bearer {{encadrant_token}}
Content-Type: application/json

{
  "email": "etudiant1@example.com",
  "nom": "Student",
  "prenom": "Etudiant",
  "password": "password123",
  "role": "Etudiant"
}

### Register as ENCADRANT (fail: cannot create admin)
POST http://localhost:4000/auth/register
Authorization: Bearer {{encadrant_token}}
Content-Type: application/json

{
  "email": "admin2@example.com",
  "nom": "Admin",
  "prenom": "Admin",
  "password": "password123",
  "role": "Admin"
}

### Register with missing fields (fail)
POST http://localhost:4000/auth/register
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "email": "missingfields@example.com"
}

### Register with duplicate email (fail)
POST http://localhost:4000/auth/register
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "email": "encadrant1@example.com",
  "nom": "Mentor",
  "prenom": "Encadrant",
  "password": "password123",
  "role": "Encadrant"
}

### Register as ETUDIANT (fail: insufficient permissions)
POST http://localhost:4000/auth/register
Authorization: Bearer {{etudiant_token}}
Content-Type: application/json

{
  "email": "fail@example.com",
  "nom": "Fail",
  "prenom": "Fail",
  "password": "password123",
  "role": "Etudiant"
} 

### Register as INCUBE (success)

POST http://localhost:4000/auth/register
Authorization: Bearer {{encadrant_token}}
Content-Type: application/json

{
  "email": "frihaouimohamed@gmail.com",
  "nom": "incube",
  "prenom": "incube",
  "password": "password123",
  "role": "Incube"
}